[package]
name = "windowpicker"
version = "0.1.0"
edition = "2021"
[[bin]]
name = "bin"
path = "src/bin.rs"

[dependencies]
willhook = "0.6.3"
windows = { version = "0.59.0", features = ["Win32_Graphics_Gdi", "Win32_UI_WindowsAndMessaging"], default-features = false }
winit = "0.30.8"
